version: '3'
networks:
  development:
  test:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  solo_customer_template_db:
    image: postgres:17.5-alpine
    container_name: solo_customer_template_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5099:5432
  solo_customer_template_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: solo_customer_template_app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    environment:
      RAILS_ENV: development
    depends_on:
      - solo_customer_template_db
